name: Build and push images
on:
  push
  branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Bazel
      uses: abhinavsingh/setup-bazel@v3
      with:
        version: 3.4.1

    - name: Build dpkg_parser
      run: bazel build //package_manager:dpkg_parser.par

    - name: Build Erlang images
      run: |
        bazel run experimental/erlang:erlang_root_amd64_debian10
        bazel run experimental/erlang:debug_root_amd64_debian10

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push Erlang images
      run: |
        bazel run experimental/erlang:push_erlang_root_amd64_debian10
        bazel run experimental/erlang:push_debug_root_amd64_debian10
